authors:
  jaseci:
    name: Jaseci
    description: Creator
    avatar: https://www.jaseci.org/wp-content/uploads/2024/05/Jaseci-logo.png
  forbes:
    name: Forbes
    description: Writer
    avatar: https://www.jaseci.org/wp-content/uploads/2022/07/forbes-logo.png
  nvidia:
    name: Nvidia
    description: Writer
    avatar: https://www.jaseci.org/wp-content/uploads/2022/06/nvidia-logo.png
  v75:
    name: V75 Incorparated
    description: Writer
    avatar: https://www.jaseci.org/wp-content/uploads/2022/07/v75.jpg
